### ISSUE TITLE
Parameters in step macro instead of REGEX_PARAM

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#112]
Transform...

```
GIVEN("^I have entered (\\d+) into the calculator$") {
    REGEX_PARAM(double, n);
    ScenarioScope<CalcCtx> context;

    context->calc.push(n);
}
```

...into

```
GIVEN("^I have entered (\\d+) into the calculator$", double n) {
    ScenarioScope<CalcCtx> context;

    context->calc.push(n);
}
```

**Comment by konserw** [comment]
@muggenhor - maybe you should assign this one to yourself as I believe you are working on this issue in PR #159 

BTW: Have you or @paoloambrosio considered using "projects" feature of github? I've never used it, but seems to be good way of organising work :)

**Comment by muggenhor** [comment]
@konserw thanks for pointing this out.

And no, I haven't considered using the 'projects' feature. I'm not sure that will become usable until we're actually dealing with a large flood of issues or PRs, and this is the kind of project that shouldn't see those (because it's scope is pretty limited).
