### ISSUE TITLE
clang >= 3.7 incompatibility

### ISSUE THREAD

**Issue by konserw** [cucumber/cucumber-cpp#119]
Hello,
I've just noticed 2 problems when compiling with clang version 3.8.1 on GNU/Linux (most probably problem exists for clang >= 3.7 both on Linux and  MAC) 
- WireProtocols test are generating such warning:
  `expression with side effects will be evaluated despite being used as an operand to 'typeid'`
  on lines where `EXPECT_PTRTYPE` macro is used
- SocketServer tests are failing with some exception: 
  `The following tests FAILED:
   21 - SocketServerTest.exitsOnFirstConnectionClosed (OTHER_FAULT)
   22 - SocketServerTest.moreThanOneClientCanConnect (OTHER_FAULT)
   23 - SocketServerTest.receiveAndSendsSingleLineMassages (OTHER_FAULT)`

Those 2 issues may or may not be connected with each other. Everything works perfectly fine using gcc 6.1.1 and of course on our CI builds.

I'm not sure how to fix that, but please let me know if I can help with this ;)

**Comment by konserw** [comment]
Socketserver tests appear to be fixed by #120 - not sure how. But warnings are still to be investigated in my opinion.
BTW. I'm very curious how #120 fixed those tests ;)

**Comment by paoloambrosio** [comment]
@konserw what Linux distro are you using? I can't reproduce it on Ubuntu with clang++ 3.8.0-2ubuntu4

**Comment by konserw** [comment]
Arch Linux (Antegros)
clang --version
clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

But the warning is also visible on travis OSX jobs, for instance: https://travis-ci.org/cucumber/cucumber-cpp/jobs/214419938

**Comment by paoloambrosio** [comment]
I must have done something wrong the first time. Now I can see the warning :-)
