### ISSUE TITLE
Code Coverage?

### ISSUE THREAD

**Issue by dbzVT8** [cucumber/cucumber-cpp#123]
Ruby-based Cucumber uses the Rake task to perform code coverage. Any interest in implementing code coverage for cucumber-cpp?

**Comment by paoloambrosio** [comment]
It could be a good idea. What tools are you thinking about?

**Comment by dbzVT8** [comment]
No I do not have any recommendations for a specific tool because I do not know exactly how best to integrate it into cucumber-cpp. I am rather new to Cucumber in general and I have next to no Ruby experience so looking at how code coverage is implemented into Ruby-based Cucumber doesn't help me gain insight into how it can be done on the cpp side.  However, without knowing the best way to integrate, I would say the two tools that do come to mind are maybe COVTOOL or CppUnit.
