### ISSUE TITLE
StepManager.hpp causes C4512 warning for each step definition in Visual Studio

### ISSUE THREAD

**Issue by mpjmpj** [cucumber/cucumber-cpp#127]
This occurs on Visual Studio 2013, x64 (probably others).
StepInfo contains a const member variable.  The compiler can't generate an assignment operator for it.  This causes a warning.  It generates a warning for each  step definition.  

There are no problems with functionality.  Just annoying warnings.  A simple fix is to create a private definition of the assignment operator to tell the compiler to knock it off.  

```
[redacted file name].cpp(34) : see reference to function template instantiation 'int cucumber::internal::registerStep<Y::CukeObject16>(const std::string &,const char *,const int)' being compiled
[redacted]\src\cucumber-cpp\include\cucumber-cpp\internal\step/StepManager.hpp(142): warning C4512: 'cucumber::internal::StepInvoker<T>' : assignment operator could not be generated
9>          with
9>          [
9>              T=Y::CukeObject17
9>          ]
9>          [redacted]\src\cucumber-cpp\include\cucumber-cpp\internal\step/StepManager.hpp(177) : see reference to class template instantiation 'cucumber::internal::StepInvoker<T>' being compiled
9>          with
9>          [
9>              T=Y::CukeObject17
9>          ]
9>          [redacted file name](41) : see reference to function template instantiation 'int cucumber::internal::registerStep<Y::CukeObject17>(const std::string &,const char *,const int)' being compiled
```

**Comment by paoloambrosio** [comment]
Any idea why this doesn't happen in VS 2015 (used by the CI build on AppVeyor)?

**Comment by mpjmpj** [comment]
No, I don't.  I poked around cmake, and didn't see anything that might turn off that warning.   My only guess is that the cucumber-cpp build is not building a test that exercises the StepInvoker template class in the same way that I am.   

https://msdn.microsoft.com/en-us/library/hsyx7kbz.aspx
MS specifically calls out that if you have a const member variable in a base class, it will not be able to generate an assignment operator for the derived class.  StepInvoker is the only class that inherits from StepInfo, which has a const member.  I'd think if it were being used, it would throw that warning. 

I'll try to poke around a bit more and see if I can generate a test that throws the warning.  

Is there a guide for the contributing to cucumber cpp?  I'm trying to figure out how to build and run things just like the build would do.  I might just be missing it though.

**Comment by paoloambrosio** [comment]
The `CONTRIBUTING.md` file in the project root does not explicitly say how to build the project like the CI pipeline. On Windows we use AppVeyor, that gets triggered for every PR and provides the shields in the main page. Configuration is in the `appveyor.yml` file. You can find the build logs for your PR #128 by following the link in the PR itself, including commands that were run: https://ci.appveyor.com/project/paoloambrosio/cucumber-cpp-qqrt7/build/master-ci-51
