### ISSUE TITLE
C++ Build on VS2017 cannot find boost

### ISSUE THREAD

**Issue by Bluesman74** [cucumber/cucumber-cpp#137]
When I first attempted to the build it said it couldn't find boost.  I tried using the switch described in the Wiki (https://github.com/cucumber/cucumber-cpp/wiki/Primer) but I'm getting an 'Invalid escape sequence \D'

`cmake -E chdir build cmake -DBOOST_ROOT=E:\Documents\Programming\Code\Libraries\boost_1_63_0 -DCUKE_ENABLE_EXAMPLES=on ..`

```
CMake Error at C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:903 (list):
  Syntax error in cmake code at

    C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:903

  when parsing string

    E:\Documents\Programming\Code\Libraries\boost_1_63_0/lib${_arch_suffix}-msvc-15.0

  Invalid escape sequence \D
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.8/Modules/FindBoost.cmake:1379 (_Boost_UPDATE_WINDOWS_LIBRARY_SEARCH_DIRS_WITH_PREBUILT_PATHS)
  CMakeLists.txt:68 (find_package)


-- Configuring incomplete, errors occurred!
See also "E:/Documents/Programming/Code/Libraries/cucumber-cpp/build/CMakeFiles/CMakeOutput.log".
See also "E:/Documents/Programming/Code/Libraries/cucumber-cpp/build/CMakeFiles/CMakeError.log".
```

I'm not sure why the _arch_suffix is unexpanded, then again I haven't really got any experience in using CMAKE

**Comment by paoloambrosio** [comment]
I would verify that you have compiled Boost with VS 2017 (no precompiled binaries exist for VS 2017 up to the latest release 1.63), and that you are using the latest CMake.

Questions are better asked on the Google Group (as written in the readme file) or on the Gitter chat. So I'm going to close this issue. Feel free to use one of the other channels for a followup.

**Comment by konserw** [comment]
> I would verify that you have compiled Boost with VS 2017 (no precompiled binaries exist for VS 2017 up to the latest release 1.63), and that you are using the latest CMake.

Normally I would agree with you @paoloambrosio but VS 2017 is binary compatible with libs built with VS 2015:

>  if you have a library built with the v140 platform toolset, that binary and your code consuming it will continue to work even if you built your code with the v141 MSVC toolset.

https://blogs.msdn.microsoft.com/vcblog/2017/03/07/binary-compatibility-and-pain-free-upgrade-why-moving-to-visual-studio-2017-is-almost-too-easy/

> Questions are better asked on the Google Group (as written in the readme file) or on the Gitter chat. So I'm going to close this issue. Feel free to use one of the other channels for a followup.

Probably gitter is best place for getting help.
