### ISSUE TITLE
Build failure on QNX with "Dinkum" STL

### ISSUE THREAD

**Issue by muggenhor** [cucumber/cucumber-cpp#156]
Attempting to build with the QNX SDK and "Dinkum" C++ standard library implementation results in this compile error:

    include/json_spirit/json_spirit_writer_template.h:80:38: error: there are no arguments to 'iswprint' that depend on a template parameter, so a declaration of 'iswprint' must be available [-fpermissive]

That's the result of:

1. not including the header that defines this function (`<wctype.h>` on C, `<cwctype>` on C++)
2. when using the C++ header: not using this method from the `std::` namespace because that's where the C++ standard requires it to be present: http://en.cppreference.com/w/cpp/string/wide/iswprint

**Comment by mhtouchette** [comment]
Hello,
Since you fixed a bug for qnx support, I'm assuming that you managed to compile and use cucumber-cpp on a qnx target.  Any chance you might want to share how you did that?

**Comment by muggenhor** [comment]
Hi @mhtouchette. I can confirm that this builds on QNX, as it's part of our company's CI. But after investigating (had to look at the CI scripts themselves) I discovered that we're not executing the tests on QNX. It should be possible though, unfortunately I don't have any direct access to QNX hardware myself to try setting this up. More importantly though I lack the development experience for that platform to justify spending time on setting this up here.

**Comment by mhtouchette** [comment]
Ok, still good to know that it should be feasible.  Thanks!
