### ISSUE TITLE
Account for AppVeyor

### ISSUE THREAD

**Issue by konserw** [cucumber/cucumber-cpp#163]
I think we should rethink what account do we use for appveyor. Currently it is Paolo's account: https://ci.appveyor.com/project/paoloambrosio/cucumber-cpp-qqrt7/history while we could use organization's account: (I have even created project) https://ci.appveyor.com/project/cucumberbdd/cucumber-cpp

**Comment by paoloambrosio** [comment]
Sorry I missed this issue earlier.

Guess I just forgot to change the build integration and the link in the README. It looks like `cucumberbdd/cucumber-cpp` has been working for a while.

Let's check everything is fine and switch to that once we have a working CI build.

**Comment by paoloambrosio** [comment]
We'll have to remove the webhook building on my account as well, but at the moment I don't know which of the two it is (and on a mobile phone so a bit impractical to check).

**Comment by mattwynne** [comment]
I suggest we move the build over to GitHub Actions where it's easy to get a Windows build.

**Comment by ursfassler** [comment]
I removed the AppVeyor build with #271. If somebody likes to add Windows or Mac to the CI build, it should be with github actions.
