### ISSUE TITLE
boost::thread::timed_join deprecated since ~1.53 (removed since... a while)

### ISSUE THREAD

**Issue by helmesjo** [cucumber/cucumber-cpp#171]
[thread::timed_join](https://github.com/cucumber/cucumber-cpp/blob/1bdae4a76df7ebf490ffaf7f61588764aabcdfbb/tests/integration/WireServerTest.cpp#L35) should be changed to either [_timed_join_for_](http://www.boost.org/doc/libs/1_61_0/doc/html/thread/thread_management.html#thread.thread_management.thread.try_join_for) or [_timed_join_until_](http://www.boost.org/doc/libs/1_65_1/doc/html/thread/thread_management.html#thread.thread_management.thread.try_join_until) according to [documentation](http://www.boost.org/doc/libs/1_65_1/doc/html/thread/thread_management.html#thread.thread_management.thread.timed_join).

Could be worth considering moving to std::thread & C++11 in general to minimize the dependencies on boost as much as possible.

I'd love to add a pull request, but currently got my hands full so thought a quick but concrete issue could help give a head-start.

OT: Great job!

**Comment by muggenhor** [comment]
Unfortunately we're currently still supporting Boost 1.46 which doesn't have either of the `try_join_XXX` functions. We can solve that by using the preprocessor though.

As for C++11: we're currently still supporting C++98 (hence the heavy dependency on Boost).

For Boost I don't mind upgrading, I do have a single project at work that's using C++98 still though and another that's relying on a platform that only has GCC 4.7.3 (buggy C++11 support). I would kind of like to be able to keep on using Cucumber-CPP on these. The C++98 part can probably be dropped soon, the same isn't true for GCC 4.7.3 though (depends on a hardware manufacturer upgrading their SDK). And those are just my considerations, I'm not aware of all the other users of this project.

**Comment by helmesjo** [comment]
Totally understandable, and often the case with a lot of projects so a good guess is that more people share your situation.

How feature-complete is the current version for your (most?) needs? Could possibly a legacy-branch be created, and master steered towards C++1x? Branches rarely get the same love as main trunk, but maybe it could be a good-enough compromise?

Not critical for me personally a the moment, but some kind of strategy for this could good to have.

Anyways, thanks for clarifying!

**Comment by paoloambrosio** [comment]
Choosing which version of Boost and the C++ standard to support has always been a big issue, as we don't know what our users are using. Don't want to cut off users that can't upgrade because of restrictions in toolchains they have to use.

For the problem at hand, I guess Boost 1.51, that has `try_join_XXX` and would allow us to remove the if statement in the main CMake file, is old enough not to be a problem for anyone :-)

I'm very much against a "backward compatibility" branch. It would just be a complete nightmare to maintain, and the effort would be worse than keeping it in the `master` branch.

**Comment by helmesjo** [comment]
Actually in my case when building from source with [boost-cmake](https://github.com/Orphis/boost-cmake)), as noted by @Orphis in the thread referenced above, just defining BOOST_THREAD_USES_DATETIME (`add_definitions(-DBOOST_THREAD_USES_DATETIME=1)` which re-enables the missing function in question did the trick (*kind of)!

*Consider moving towards _modern_ cmake, that is: Use the new 'target'-methods and correct target-aliases instead of manually including directories etc. 

Eg: 
 - `target_include_directories` instead of `include_directories`
 - `Boost::boost` instead of `Boost_INCLUDE_DIR` (same goes for all the boost-targets, `Boost::thread` instead of `Boost_THREAD_LIBRARY` etc.)

This makes the framework a lot more portable, and the CMake-scripts _a lot cleaner_.
