### ISSUE TITLE
Bow-shaped branches

### ISSUE THREAD

**Issue by konserw** [cucumber/cucumber-cpp#172]
## Summary

Let's consider git workflow with [Bow-shaped branches](http://pdh11.blogspot.com/2013/06/bow-shaped-branches-git-workflow.html)
I think it's pretty close to what we have now, but not strictly.
It would result in more visible groups of commits from same PR/feature
What do you think?

**Comment by muggenhor** [comment]
I believe we're already doing this for PRs. With the exception that the these just before merging is done only if there are merge conflicts. I think that's better because it better preserves the history that was the reality during development.

**Comment by konserw** [comment]
So it's no longer this workflow as we have had at times 4-5 parallel lines in git log. What this is about is to have at all times only two. 
Is that information on which PRs has been developed in parallel so important? If so we are already loosing it in the process of rebasing PRs when there is merge conflict or even after a review.

**Comment by muggenhor** [comment]
> Is that information on which PRs has been developed in parallel so important?

It's not about which have been developed in parallel, it's about what the parent commit was on top of which the development took place: that's the original context. This can sometimes be quite important for understanding why a piece of code was written the way it was. The only difference would seem to be that you don't have the parallel lines in `gitk` with that bow-approach, that seems like a very minor advantage to me, more of a cosmetic nature than anything else.

**Comment by konserw** [comment]
Ok, fair enough

**Comment by paoloambrosio** [comment]
In the current situation, where we rarely have too many branches at the same time, I don't mind either way. I would ask contributors to rebase to master when the PR commits are too spread out, but I would not enforce a specific workflow: it might cause more trouble than it's worth.

**Comment by konserw** [comment]
Ok -> closing
