### ISSUE TITLE
Impossible to get the tests working (and probably the compilation)

### ISSUE THREAD

**Issue by zadigus** [cucumber/cucumber-cpp#199]
Hi,
I carefully followed the procedure documented here: https://github.com/cucumber/cucumber-cpp. Indeed, I did

~~~
gem install bundler // For windows: gem install bundle
bundle install
~~~

and then

~~~
git submodule init
git submodule update
cmake -E make_directory build
cmake -E chdir build cmake -DCUKE_ENABLE_EXAMPLES=on -DCMAKE_INSTALL_PREFIX=C:/myPath ..
cmake --build build
~~~

Up to here I get zero errors and 7 warnings [build.log](https://github.com/cucumber/cucumber-cpp/files/2290533/build.log).

When I now do

~~~
cmake --build build --target test
~~~

I get 

~~~
Microsoft (R) Build Engine version 4.6.1590.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: test.vcxproj
~~~

and when I do

~~~
cmake --build build --target features
~~~

I get [test.log](https://github.com/cucumber/cucumber-cpp/files/2290539/test.log).

I am working under Windows 10 with Visual Studio 2010 and boost 1.57. Does anyone have a hint what I am doing wrong?

**Comment by zadigus** [comment]
Here you can also see my [CMakeCache.txt](https://github.com/cucumber/cucumber-cpp/files/2290548/CMakeCache.txt)

**Comment by zadigus** [comment]
I gave it a try again today. I downloaded the latest release you have (version 0.5) and got the [èèèfollowing result](https://github.com/cucumber/cucumber-cpp/files/2293393/features-2.txt) with a 
~~~
cmake --build build --target features
~~~
Is it fine? What can I do about 
~~~
CUSTOMBUILD : warning : cannot load such file -- 2.5/gherkin_lexer_en [D:\workspace\cucumber-cpp-0.5\build\features.vcxproj]
~~~
?

**Comment by sergey-bon** [comment]
> Is it fine? What can I do about
> 
> ```
> CUSTOMBUILD : warning : cannot load such file -- 2.5/gherkin_lexer_en [D:\workspace\cucumber-cpp-0.5\build\features.vcxproj]
> ```

You are missing `gherkin` gem. This should fix it:

```
gem install gherkin
```

**Comment by 2BlackCoffees** [comment]
Hi, I have the same problem on 
Windows 10
cmake version 3.13.4
Visual Studio 2017
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

Any update ?

Thanks,

**Comment by zadigus** [comment]
I saw nothing new on that topic. I guess the project is dead ... I am now using SpecFlow instead.

**Comment by syaifulnizamyahya** [comment]
I have the same problem. No fix so far. Any hints?

**Comment by jermus67** [comment]
Hello,

Support _is_ being picked up again, but unfortunately for Windows users by an engineer who mainly develops on Linux. I do not have a windows build environment in place. Until I get around to install a windows build environment, or until another windows maintainer steps in I am afraid that support for building cucumber-cpp on Windows will be neigh to non-existent. I have no personal need for cucumber-cpp on Windows, so installing a Windows development environment and making cucumber-cpp work in that environment is not on the top of my to-do list.

Maybe some of the contributors to this issue are interested in stepping in to help maintain cucumber-cpp for Windows?

Kind regards,
Jeroen Kouwer

**Comment by ursfassler** [comment]
Please reopen this issue if it is not resolved for you.
In the case it works for you, I would appreciate if you can help others by doing one or more:

- Add your solution here
- Add Windows to the CI (with a github action) that:
  - compiles cucumber-cpp
  - runs the tests
  - runs the examples
