### ISSUE TITLE
Cannot open source file cpp_steps.cpp

### ISSUE THREAD

**Issue by MonikaPa** [cucumber/cucumber-cpp#202]
I am trying to build cucumber_cpp. Boost library being used is boost_1_66_0.
While building I am getting this error
"c1xx : fatal error C1083: Cannot open source file: 'C:\Cucumber\cucumber-cpp\vsprj\tmp\test_features\step_definitions\cpp_steps.cpp': No such file or directory"
Also I do not see BoostCalculatorSteps.exe in
vsprj\examples\Calc\Debug

I used this command to make cucumber-cpp VS solution
cmake -E chdir vsprj cmake -G"Visual Studio 14 2015" -DUKE_ENABLE_EXAMPLES=on -DBOOST_ROOT=C:\Boost ..

Can Anyone suggest what may be wrong?

**Comment by paoloambrosio** [comment]
That file is generated in a temporary directory by the end-to-end test suite (targets `features`, `features-wip` and `features-pretty`) for each scenario, compiled, and then run as part of the test. As such, it is not present in the source code and won't be found by Visual Studio.

I would suggest to run the CMake project generation with `-DCUKE_DISABLE_E2E_TESTS=on` when generating a project for an IDE. That flag should remove all build targets that references that source file.

**Comment by MonikaPa** [comment]
Thank you @paoloambrosio  it has compiled now. But I do not see any BoostCalculatorSteps.exe .
Also as mentioned on https://infowarestudios.co.za/agile-testing-getting-agile-tests-incorporated-into-your-sprints-using-bdd-and-cucumber-in-c/ 
the **vsprj** has no cd examples folder . There does not exist any path saying cd vsprj\examples\Calc\Debug

**Comment by paoloambrosio** [comment]
Check the spelling: in the line you pasted above you had ` -DUKE_ENABLE_EXAMPLES=on`, while it should be ` -DCUKE_ENABLE_EXAMPLES=on`. With that, I can see the `BoostCalculatorSteps` solution on Visual Studio.

As these are not bugs, I will close the issue and ask you to use the help channels documented here: https://docs.cucumber.io/community/get-in-touch/

I'll also raise a PR to update them at the top of the main README file.
