### ISSUE TITLE
Why it found the feature file but doesn't found the step definitions?

### ISSUE THREAD

**Issue by Ingvanegas** [cucumber/cucumber-cpp#219]
## Summary

I use cuucumber-cpp on my project and get me this result
![image](https://user-images.githubusercontent.com/3432316/52671986-7e6fec80-2eea-11e9-9f91-21f09c601e24.png)

**Comment by muggenhor** [comment]
Do you have a `step_definitions/cucumber.wire` file near your feature files?

**Comment by konserw** [comment]
From my expirience it's wrong ruby/cucmber versions combination

**Comment by ChrisCAdsk** [comment]
@konserw Do you know what is the correct cucumber-cpp / ruby versions combination? I have installed cucumber gem 3.1.2 and I'm running a cucumber-cpp 0.5 executable containing step definitions along with the gem and I'm getting all steps undefined.
This doesn't happen with ruby 2.3.3 x64 + devkit, it doesn't work without the devkit installed either.

**Comment by konserw** [comment]
cucumber-ruby 2.4.0, see #179 and #194

**Comment by konserw** [comment]
also cucumber-cpp own README: 

> Please mind that Cucumber-Cpp is not compatible with Cucumber-Ruby 3.x due to a bug in its wire protocol implementation.

**Comment by ChrisCAdsk** [comment]
I think I may have a different issue because it's not working for me with cucumber (ruby) 2.4.0.
There is no logging from the wire protocol so I can't be sure what the issue is. The app that contains the tests has the wire port listening, so the issue is likely on the cucumber side.
I'm going to try with cucumber 2.0.0 using ruby 2.3 x64 and the associated devkit for 2.3.

**Comment by jermus67** [comment]
Hello,

@Ingvanegas and @ChrisCAdsk , any luck getting cucumber-cpp to work? Not that I'm in the best position to help when things still don't work... I'm mainly developing on GNU/Linux, so the latest support is also mostly focused on getting cucumber-cpp working in that environment again. You are of course more than welcome to step in and help in maintaining cucumber-cpp for windows... :)

Kind regards,
Jeroen Kouwer

**Comment by ursfassler** [comment]
Because the step implementations are only suggested in Ruby and not C++, this seems to be a problem with the configuration of cucumber itself. Most likely a wrong configuration with the cucumber.wire file as mentioned in https://github.com/cucumber/cucumber-cpp/issues/219#issuecomment-463609265.

**Comment by ursfassler** [comment]
Please reopen this issue if it is not resolved for you.
In the case it works for you, I would appreciate if you can help others by doing one or more:

- Add your solution here
- Add Windows to the CI (with a github action) that:
  - compiles cucumber-cpp
  - runs the tests
  - runs the examples
