### ISSUE TITLE
feature doesn't found the step definitions?

### ISSUE THREAD

**Issue by zxh8509304** [cucumber/cucumber-cpp#220]
![image](https://user-images.githubusercontent.com/22524236/56798767-0a3ab900-684a-11e9-8239-fa7ef48c6cac.png)
cucumber v  2.4.0
ruby v 2.6.3

**Comment by zxh8509304** [comment]
![image](https://user-images.githubusercontent.com/22524236/56798933-6b628c80-684a-11e9-9963-609a025165c5.png)
![image](https://user-images.githubusercontent.com/22524236/56798945-71586d80-684a-11e9-9a0e-b33c350a7b2f.png)

**Comment by zxh8509304** [comment]
I have all the documents，But no steps were found.

**Comment by zxh8509304** [comment]
![image](https://user-images.githubusercontent.com/22524236/56849605-3d07ae80-6929-11e9-9a7a-c08569e6a982.png)
why cpp hide ？？？

**Comment by sunpian1** [comment]
你遇见过这个情况吗？https://github.com/cucumber/cucumber-cpp/issues/256

**Comment by ursfassler** [comment]
The missing C++ step snippets from the first screenshot indicate that cucumber isn't connected to cucumber-cpp. Please verify that you have a correct cucumber.wire file.

**Comment by ursfassler** [comment]
Please reopen this issue if it is not resolved for you.
In the case it works for you, I would appreciate if you can help others by doing one or more:
- Add your solution here
- Add Windows to the CI (with a github action) that:
  - compiles cucumber-cpp
  - runs the tests
  - runs the examples
