### ISSUE TITLE
Add Conan support for cucumber-cpp

### ISSUE THREAD

**Issue by jermus67** [cucumber/cucumber-cpp#246]
```gherkin
Feature: conan package manager support

  Rule: Using the conan package manager is optional

    Scenario: build cucumber-cpp without conan as package manager
      As a non-conan user
      I want to download and install all cucumber-cpp dependencies manually
      So that I can build and install cucumber-cpp

    Scenario: build cucumber-cpp with conan as package manager
      As a conan user
      I want to use conan to download and install all cucumber-cpp dependencies using conan
      So that I can build and install cucumber-cpp

  Rule: cucumber-cpp can be downloaded and installed as a conan dependency

    Scenario: cucumber-cpp is downloaded and installed as a conan package manager managed dependency
      As a conan-user
      I want to be able to list cucumber-cpp as conan required package
      So that, when building my own application, cucumber-cpp is downloaded and installed by the conan package manager
```

The implementation of this feature should be based on the following comments from #198 :
* [How to use conan to build cucumber-cpp without changing the CMakeLists.txt](https://github.com/cucumber/cucumber-cpp/pull/198#issuecomment-460140877)
* [Adding cucumber-cpp to the conan-center-index](https://github.com/cucumber/cucumber-cpp/pull/198#issuecomment-912392769)

The second bullet (adding cucumber-cpp to the conan-center-index) probably _does_ require altering the CMakeLists.txt, but that should be done in such a way that it doesn't affect normal builds. And of course it means adding the proper recipe to the conan-center-index (which can enable the conan-specific additions to the CMakeLists.txt to make cucumber-cpp work as a conan package.

**Comment by ursfassler** [comment]
Closing it due to old age. Please reopen when you are working on it.
