### ISSUE TITLE
[FEATURE] comparing result of performances (upload data in the report)

### ISSUE THREAD

**Issue by HeeroYui** [cucumber/cucumber-cpp#248]
I need to compare bench performances, but I know the result only when it is wrong (comparing error) 

I know the cucumber on js can upload images on the html report. I did not find a way to upload image or text un the cpp-cucumber. is it possible to add text on report or images?

**Comment by jermus67** [comment]
I'm not sure it this is possible with cucumber-cpp. However, until now the reporting relies on what is provided in cucumber ruby, as the cpp part is "just" a test steps execution engine for now (communicating with cucumber ruby over the wire protocol).

Maybe you can point me to a an example of uploading images in cucumber-js? I can then ask around to see if we can (or cannot) replicate that behavior with cucumber-cpp.

**Comment by jermus67** [comment]
@HeeroYui , I'm sorry to have say that, after having asked around, that uploading screenshots is not possible with the current implementation of cucumber-cpp, due to relying on the wire protocol, which does not support this feature.
