### ISSUE TITLE
Is there a working example of cucumber (c cmake, boost) for c++?

### ISSUE THREAD

**Issue by Gonerr** [cucumber/cucumber-cpp#257]
Hello everybody! I ran into a problem: I can't build an example [Calc](https://github.com/cucumber/cucumber-cpp ), an error appears in the step
```
# Generate Makefiles
cmake -E chdir build cmake -DCUKE_ENABLE_EXAMPLES=on -DCMAKE_INSTALL_PREFIX=${prefix} ..
```
I can't fix it in any way. I use the latest version of Cmake 3.27.0 and Boost 1.82.0, googletest is also the latest version. I tried to run it with others (Boost 1.46, Cmake 3.25), but it still gives an error:

```
-- Could NOT find Boost (missing: unit_test_framework) (found suitable version "1.46.1", minimum required is "1.46")
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: thread system regex date_time
  program_options filesystem) (found suitable version "1.46.1", minimum
  required is "1.46")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindBoost.cmake:2378 (find_package_handle_standard_args)
  CMakeLists.txt:137 (find_package)
```

File [CMakeLists.txt](https://github.com/cucumber/cucumber-cpp/files/11905280/CMakeLists.txt)
Does anyone know **which versions of Boost and Cmake the test will be built with?**

**Comment by ursfassler** [comment]
The solution from @jenisys also works for me. Make sure you disable Qt, there is another problem with missing C++11 and gtest. I have on a current debian testing:
- cmake 3.26.4
- boost 1.81.0
- googletest current head

This is a bug within cucumber-cpp, we have to enforce C++14. Thanks for figuring that out.

**Comment by ursfassler** [comment]
@Gonerr the mentioned error:

```
-- Could NOT find Boost (missing: unit_test_framework) (found suitable version "1.46.1", minimum required is "1.46")
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: thread system regex date_time
  program_options filesystem) (found suitable version "1.46.1", minimum
  required is "1.46")
```

Says that the boost modules "thread system regex date_time program_options filesystem" are missing. You may have to install them explicitly/manually.

**Comment by ursfassler** [comment]
@Gonerr @linopsa 
Please reopen this issue if it is not resolved for you.
In the case it works for you, I would appreciate if you can help others by doing one or more:
- Add your solution here
- Add Windows to the CI (with a github action) that:
  - compiles cucumber-cpp
  - runs the tests
  - runs the examples
