### ISSUE TITLE
nlohmann-json I think breaks the installation

### ISSUE THREAD

**Issue by erichstuder** [cucumber/cucumber-cpp#276]
Update: I found out I can install the package just with:
apt install nlohmann-json3-dev
Would a hint in the readme be helpfull?

### 👓 What did you see?

[nlohmann-json](https://github.com/nlohmann/json) I think breaks the installation

```
CMake Error at src/CMakeLists.txt:3 (find_package):
  By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "nlohmann_json", but CMake did not find one.

  Could not find a package configuration file provided by "nlohmann_json"
  (requested version 3.10.5) with any of the following names:

    nlohmann_jsonConfig.cmake
    nlohmann_json-config.cmake

  Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
  "nlohmann_json_DIR" to a directory containing one of the above files.  If
  "nlohmann_json" provides a separate development package or SDK, be sure it
  has been installed.
```

### ✅ What did you expect to see?

The installation downloads the stuff it needs by itself. Like gtest, ...
In the repository there are about 10 files in the release. Which one do I need? Also there seems to be not really an Installation Instruction. Where to install it best?

### 📦 Which tool/library version are you using?

debian:latest

### 🔬 How could we reproduce it?

Install on debian:latest

### Steps to reproduce the behavior:
As advised in the Readme.md

Tank you

**Comment by ursfassler** [comment]
Thanks for reporting. I'll add the info to the Readme.

Source of truth are the CI scripts (.github/workflows/run-all.yml), but they are a bit hidden.

**Comment by erichstuder** [comment]
> Thanks for reporting. I'll add the info to the Readme.
> 
> Source of truth are the CI scripts (.github/workflows/run-all.yml), but they are a bit hidden.

For me a hint to the workflow file would be fine. It also shows what other tools are necessary.
