### ISSUE TITLE
cucumber.wire ignored (older versions don't)

### ISSUE THREAD

**Issue by erichstuder** [cucumber/cucumber-cpp#277]
### 👓 What did you see?

Commit [2f7d9ad519290a8b4a6ee6845af4480dd9ec2b7f](https://github.com/cucumber/cucumber-cpp/commit/2f7d9ad519290a8b4a6ee6845af4480dd9ec2b7f) works fine.
A few commits later and also for the latest commit [01d24e8b4f07f4abb2c13a21311431f792d4bccd](https://github.com/cucumber/cucumber-cpp/commit/01d24e8b4f07f4abb2c13a21311431f792d4bccd)
it is no longer working for me.
Step definitions are no longer found.
For me it looks a bit as if the cucumber.wire file is ignored. 
No matter where I put the file, the step definitions are no longer found.
The server is started though without error as I can see.
But no connection to local host seems to happen.

Did something fundamentally change since last septembre?
It builds so far without errors or other problems.

### ✅ What did you expect to see?

Working like commit [2f7d9ad519290a8b4a6ee6845af4480dd9ec2b7f](https://github.com/cucumber/cucumber-cpp/commit

### 📦 Which tool/library version are you using?

debian:latest

### 🔬 How could we reproduce it?

I created a new project with the same outcome.

Also see: https://github.com/erichstuder/TurnTable/tree/persistency/software/firmware
Dockerfile and run_cucumber.sh
If I checkout the latest commit in the Dockerfile it is no longer working.

**Comment by ursfassler** [comment]
I am working on cucumber-cpp to modernize it. That may break some things.

However, I took a look into your project. The main thing that changed is the used cucumber version. You install it from the Gemfile, it changed from 2.0.0 to 7.1.0. Cucumber seems to have changed in a way here it doesn't find the cucumber.wire file anymore. The solution is to execute cucumber from the feature test root directory, in your case software/firmware (where the folder features is). See the change [982f06841563b3f8add6f8b5baa1b0c60bc925b1](https://github.com/ursfassler/TurnTable/commit/982f06841563b3f8add6f8b5baa1b0c60bc925b1#diff-5a25574d34bca81a859ef3f0be4ad6ce9c51f08d1c79389996a26d5cbd2ad78fR33).

**Comment by erichstuder** [comment]
Thank you for your PR!
