### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#30]
Write user documentation including an introductory guide, hooks (random execution order), contexts, and any other feature.

Edit: reworded and got rid of what was done as part of other tickets

**Comment by konserw** [comment]
Should we also add something there:
* https://github.com/cucumber/docs.cucumber.io
* https://github.com/cucumber/api.cucumber.io

**Comment by paoloambrosio** [comment]
Reopen if we ever decide to do it.
