### ISSUE TITLE
Build 64x compilation errors

### ISSUE THREAD

**Issue by kittoinc** [cucumber/cucumber-cpp#49]
Hi, I am trying to build the example test for x64 settings, and ran into couple "unresolved external symbol" when building BoostCalculatorSteps project.  Does anyone knows what is going on??  It works fine for 32-bits settings.

Setup:
* visual studio 2010
* x64 build

Note:
* All projects compile fine -- BoostDriverTest, Calc, cucumber-cpp
* I have tried creating a new project for testing and got the same error
* Also have problem trying to include boost_unit_test_framework as a static library (without BOOST_TEST_DYN_LINK flag).  Maybe someone has a working solution?

BoostCalculatorSteps project --

4>------ Rebuild All started: Project: BoostCalculatorSteps, Configuration: Debug x64 ------
4>Build started 10/26/2012 1:27:15 PM.
4>_PrepareForClean:
4>  Deleting file "BoostCalculatorSteps.dir\Debug\BoostCalculatorSteps.lastbuildstate".
4>InitializeBuildStatus:
4>  Touching "BoostCalculatorSteps.dir\Debug\BoostCalculatorSteps.unsuccessfulbuild".
4>CustomBuild:
4>  Building Custom Rule D:/git/cucumber-cpp/examples/Calc/CMakeLists.txt
4>  CMake does not need to re-run because D:\git\cucumber-cpp\build64\examples\Calc\CMakeFiles\generate.stamp is up-to-date.
4>ClCompile:
4>  BoostCalculatorSteps.cpp
4>d:\git\cucumber-cpp\include\cucumber-cpp\internal\step\../Table.hpp(21): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
4>d:\git\cucumber-cpp\include\cucumber-cpp\internal\step\../Table.hpp(22): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)

4>cucumber-cpp.lib(main.obj) : error LNK2019: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "public: __cdecl boost::system::error_code::error_code(void)" (??0error_code@system@boost@@QEAA@XZ)

4>cucumber-cpp.lib(WireServer.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::system_category(void)" (?system_category@system@boost@@YAAEBVerror_category@12@XZ)

4>cucumber-cpp.lib(main.obj) : error LNK2019: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "void __cdecl boost::system::`dynamic initializer for 'posix_category''(void)" (??__Eposix_category@system@boost@@YAXXZ)

4>cucumber-cpp.lib(WireServer.obj) : error LNK2001: unresolved external symbol "class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (?generic_category@system@boost@@YAAEBVerror_category@12@XZ)

4>D:\git\cucumber-cpp\build64\examples\Calc\Debug\BoostCalculatorSteps.exe : fatal error LNK1120: 2 unresolved externals
4>
4>Build FAILED.
4>
4>Time Elapsed 00:00:01.76
========== Rebuild All: 3 succeeded, 1 failed, 0 skipped ==========

**Comment by skizzay** [comment]
Looks like you aren't linking in the correct boost libraries.  Try boost.system.

**Comment by paoloambrosio** [comment]
#114 builds on Windows with 64-bit taget
