### ISSUE TITLE
BOOST_PREDICATE_MESSAGE(boolean, string message)

### ISSUE THREAD

**Issue by isoung** [cucumber/cucumber-cpp#81]
When using boost testing tools the messages do not show up when using the above evaluation. According to boost, if the predicate fails the custom message should appear with the failure. Instead I only receive a general message indicating failure with no string message attached. Is this a supported feature?

**Comment by konserw** [comment]
I haven't found ` BOOST_PREDICATE_MESSAGE(boolean, string message)` but there are:
```
BOOST_WARN_MESSAGE( predicate, message )
BOOST_CHECK_MESSAGE( predicate, message )
BOOST_REQUIRE_MESSAGE( predicate, message )
```
I believe those macros are what this issue is about. Indeed triggering those macros in code was not being detected by cucumber, but PR #164 should fix that.
