### ISSUE TITLE
Fix CI pipeline

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#87]
Travis fails builds because it tries to install Ruby libraries (Cucumber-Ruby, Aruba and RSpec) that are not compatible with the current code. Make sure that it builds with some old version.

Bundler should install Cucumber-Ruby 1.3.x, and will have to specify an older version of RSpec and Aruba (0.7.4 is the latest that works) in the Gemfile.

Cucumber-TCK has been updated with a feature that fails on Cucumber-CPP. Might have to block the submodule to a specific commit.

**Comment by konserw** [comment]
group :test do
  gem 'cucumber', "=1.3.6"
  gem 'aruba', "=0.5.3"
  gem 'rspec', "=2.14.1"
end
Works OK - those are versions from lat travis build. With Aruba 0.7.4 25 scenarios are failing.

**Comment by konserw** [comment]
After merging 29dc152c2c715df5982d29ca1d1a2f2037d82178 from paoloambrosio/cucumber-cpp master:
Cucumber | Aruba | rspec | # of failing scenarios
-------------|-----------|------|---------------
1.3.20 | 0.6.1 | 3.0.0 | 0
1.3.20 | 0.6.2 | 3.0.0 | 3
1.3.20 | 0.6.1 | 3.4.0 | 0

**Comment by konserw** [comment]
With commit from previous post and changes from branch konserw/cucumber-cpp/ci_merge
 
Cucumber | Aruba | rspec | # of failing scenarios
-------------|-----------|------|---------------
1.3.20 | 0.6.2 | 3.4.0 | 0
1.3.20 | 0.7.4 | 3.4.0 | 0

**Comment by konserw** [comment]
fixed Aruba 0.8.0 with commit 89b276c of ci_merge

**Comment by paoloambrosio** [comment]
Closed by #92
