### ISSUE TITLE
Upgrade to the latest Ruby version and libraries

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#88]
This should NOT require changing the Travis configuration. It should just work upgrading Ruby dependencies to the latest version and fixing Ruby step definitions.

Step definitions in Cucumber-TCK support an old version of Aruba. Could either fix that or copy it inside the project like the other implementations seem to have.

**Comment by paoloambrosio** [comment]
More info on #87

**Comment by konserw** [comment]
So what are we doing with cucumber-tck? It's quite crucial to decide as I've encountered more problems with it when working on CI for Windows and OSX, see #96 and #97

**Comment by paoloambrosio** [comment]
Good enough for now. Raised #115 to track further work needed.
