### ISSUE TITLE
Upgrade C++ dependencies

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#89]
- Latest library version should work (or a reasonably recent depending on what can be supported on CI servers)
- Earliest supported must be those in the latest Ubuntu stable (Boost 1.54, Google Mock/Test 1.6.0), latest Debian stable (Boost 1.55, Google Mock/Test 1.7.0), ...

Examples are a special case and in general they might just support the latest. Upgrade to Qt 5 is not mandatory at this stage.

Different versions might be tested on different platforms (we shouldn't be too picky at this stage).

**Comment by konserw** [comment]
GMock 1.6.0 fails - see https://travis-ci.org/konserw/cucumber-cpp/jobs/104175912 - i'm not sure how to fix it?

**Comment by konserw** [comment]
GMock 1.6 issue fixed with commit 47c8be604e43bea729c6b7c35d7bcbdf55966fa5

**Comment by kai-unger** [comment]
I adapted the boost driver to support the latest boost version 1.60 in my [fork of cucumber-cpp](https://github.com/kai-unger/cucumber-cpp).

I tested it with ctest and running BoostCalculatorSteps with cucumber 2.0.0 on OS X 10.11.3 (system compiler clang) with boost versions 1.54, 1.58, 1.59 and 1.60. #101
