### ISSUE TITLE
CI for OSX and Windows

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#90]
Travis now supports OSX
AppVeyor supports Windows

**Comment by konserw** [comment]
osx travis build is part of #86 pull request

**Comment by konserw** [comment]
I've created PRs that should solve this ;) 
 Appveyor - windows CI #97 
 Travis - OSX CI #96

**Comment by paoloambrosio** [comment]
OSX CI introduced with #104

**Comment by paoloambrosio** [comment]
Windows CI introduced with #114 (can be improved)
