### ISSUE TITLE
Use GTest/GMock CMakeLists instead of FindGTest/FindGMock

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber/cucumber-cpp#91]
It should read like before, but including gtest/gmock's cmake file instead. Users should also be able to configure the path where their version of GTest has been installed, without downloading it (e.g. Ubuntu comes with a package).

Look at changes in #86

**Comment by konserw** [comment]
Debian and ubuntu packages are source only, as google does not recomend
distribution o binary shared libraries. They recommend compilation from
source for each project as some compile-time flags may broke gtest runetime
14 sty 2016 08:26 "Paolo Ambrosio" <notifications@github.com> napisał(a):

**Comment by paoloambrosio** [comment]
Yes indeed. For that reason, instead of forcingly downloading 1.7.0 in CMake we should give the OPTION for the user to specify where GTest/GMock sources are present, instead of assuming that the user does not know what he/she is doing.

**Comment by konserw** [comment]
Point taken.

2016-01-14 13:57 GMT+01:00 Paolo Ambrosio <notifications@github.com>:

**Comment by konserw** [comment]
I'm working on it in branch new_gtest feel free to comment it :)
